name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: geckodriver/firefox
      run: |
        echo "geckodriver/firefox"
        which geckodriver
        geckodriver --version
        which firefox
        firefox --version
    - name: Install Dependencies
      run: |
        cat Pipfile
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
    - name: Run Tests
      run: |
        pipenv run python manage.py makemigrations
        pipenv run python manage.py test
        nohup pipenv run python manage.py runserver 8080 > /dev/null 2>&1 &
        ls -l
        chmod +x function_test.sh
        ./function_test.sh
